import { Metadata } from "next";
import React, { Suspense } from "react";
import { RefineProvider } from "@/components/refine-provider";
import "@styles/global.css";


export const metadata: Metadata = {
  title: "Refine",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Suspense>
          <RefineProvider>
            {children}
          </RefineProvider>
        </Suspense>
      </body>
    </html>
  );
}
